on:
  push:
    branches: [ api_client_28_05 ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential clang-tidy-12 clang-format-12 gcc-11 g++-11
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11
          sudo wget https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.tar.gz
          sudo tar -xf boost_1_79_0.tar.gz -C /usr/local/include/
          sudo apt-get install -y qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
      - name: Cmake
        run: |
          cd api_client
          mkdir build
          cd build
          cmake ..
          cmake --build .
          