on:
  push:
    branches: [ ml_28_05, build_server ]
  pull_request:
    branches: [ main ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd ML
          make packages
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd ML
          make packages
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd ML
          make packages